//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LOAIDAILY
    {
        public int MaLoai { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Cấp")]
        public Nullable<int> Cap { get; set; }

        [DisplayName("Mục Chiết Khấu")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string MucChietKhau { get; set; }

        [DisplayName("Xóa")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public Nullable<bool> isXoa { get; set; }
    }
}
