//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        public int MaNV { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Họ Tên")]
        public string Hoten { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Ngày Sinh")]
        public Nullable<System.DateTime> Ngaysinh { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Giới Tính")]
        public Nullable<bool> Gioitinh { get; set; }

        [DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Ngày Vào Làm")]
        public Nullable<System.DateTime> Ngayvaolam { get; set; }

        [DisplayName("Xóa")]
        public Nullable<bool> isXoa { get; set; }
    }
}
