//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TAIKHOAN
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Tài Khoản")]
        public string TaiKhoan1 { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Mật Khẩu")]
        [DataType(DataType.Password)]
        public string MatKhau { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Họ Tên")]
        public string HoTen { get; set; }
        public Nullable<bool> ISADMIN { get; set; }
    }
}
