//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DONHANGXUAT
    {
        [DisplayName("Mã")]
        public int MaDHX { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Đại Lý")]
        public int MaDaiLy { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Nhân Viên")]
        public Nullable<int> MaNV { get; set; }

        [DisplayName("Trạng Thái")]
        public Nullable<bool> TrangThai { get; set; }


        [DisplayName("Sản Phẩm")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string [] MaSP { get; set; }

        [DisplayName("Số Lượng")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int SoLuong { get; set; }

        [DisplayName("Tram")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public int Tram { set; get; }
        [DisplayName("Xóa")]
        public Nullable<bool> isXoa { get; set; }

        public Nullable<int> ThoiGian { get; set; }
        public string PhuongTien { get; set; }
    }
}
