//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SANPHAM
    {
        public int MaSP { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Loại")]
        public Nullable<int> MaLoai { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("NCC")]
        public Nullable<int> MaNCC { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Tên")]
        public string TenSP { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Trọng Lượng")]
        public Nullable<double> TrongLuong { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("HSD")]
        public Nullable<short> ThoiHanSuDung { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Quy Cách")]
        public string QuyCachDongGoi { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Giá")]
        public Nullable<double> Gia { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Ghi Chú")]
        public string Ghichu { get; set; }

        [DisplayName("Xóa")]
        public Nullable<bool> isXoa { get; set; }
        public string ThoiGian { get; set; }
        public string BaoQuan { get; set; }
    }
}
