//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SQLGOIY
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Table")]
        public string NameTable { get; set; }
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Tên gợi ý")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Truy vấn sql")]
        public string SqlString { get; set; }
    }
}
