//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TRAM
    {
        [DisplayName("Mã")]
        public int MaTram { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [DisplayName("Tên")]
        public string TenTram { get; set; }

        [DisplayName("Xóa")]
        public Nullable<bool> isXoa { get; set; }
    }
}
